CREATE SEQUENCE SEQ_STREET
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_STREET (
    STREET_ID Integer PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    cep VARCHAR2(9) NOT NULL
);