on:
  push:
    branches:
      - develop
      - staging

env:
  IMAGE_NAME: traffic-management
  AZURE_WEBAPP_NAME: traffic-management

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    environment:
      name: development
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiap-traffic-management'
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: "ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    environment:
      name: staging
      url: ${{ steps.deploy-to-webapp-staging.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App (Staging)
        id: deploy-to-webapp-staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiap-traffic-management-homol'
          publish-profile: ${{ secrets.AZURE_PROFILE_STAGING }}
          images: "ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
